# Generated by Django 5.0.14 on 2025-12-04 14:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_strategy_alter_subscription_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayPalPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paypal_order_id",
                    models.CharField(
                        help_text="PayPal order/transaction ID",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "paypal_subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="PayPal subscription ID if applicable",
                        max_length=255,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Payment amount", max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (USD, EUR, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription Payment"),
                            ("one_time", "One-Time Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "webhook_data",
                    models.JSONField(
                        blank=True, help_text="Raw PayPal webhook payload", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrialAbuseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("machine_id_hash", models.CharField(db_index=True, max_length=64)),
                ("strategy_name", models.CharField(max_length=255)),
                (
                    "attempted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "blocked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this attempt was blocked as suspicious",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="downloadevent",
            name="strategy",
        ),
        migrations.RemoveField(
            model_name="downloadevent",
            name="user",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="strategy",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="strategy",
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={},
        ),
        migrations.AlterModelOptions(
            name="trial",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="trial",
            unique_together={("user", "strategy_name")},
        ),
        migrations.AddField(
            model_name="subscription",
            name="bundle_strategies",
            field=models.JSONField(
                blank=True,
                help_text="List of strategy names if this is a bundle purchase",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="next_billing_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Next billing date for recurring subscriptions",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="paypal_plan_id",
            field=models.CharField(
                blank=True, help_text="PayPal plan ID", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="trial",
            name="deactivated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the trial was deactivated (expired or converted).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("rental", "Monthly Rental"),
                    ("lifetime", "Lifetime Purchase"),
                    ("bundle", "Bundle Purchase"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="paypal_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="PayPal subscription ID for recurring payments",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                    ("payment_failed", "Payment Failed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="strategy_name",
            field=models.CharField(
                help_text="Single strategy name, or 'Bundle' for multiple strategies",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="trial",
            name="machine_id_snapshot",
            field=models.CharField(
                db_index=True,
                help_text="SHA-256 hash of machine ID at the time the trial started.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="trial",
            name="strategy_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user", "status"], name="payments_su_user_id_058311_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["status", "ends_at"], name="payments_su_status_7de9ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trial",
            index=models.Index(
                fields=["machine_id_snapshot", "strategy_name"],
                name="payments_tr_machine_5bc65c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trial",
            index=models.Index(
                fields=["status", "ends_at"], name="payments_tr_status_b4198c_idx"
            ),
        ),
        migrations.AddField(
            model_name="paypalpayment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="payments.subscription",
            ),
        ),
        migrations.AddField(
            model_name="paypalpayment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paypal_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trialabuselog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="DownloadEvent",
        ),
        migrations.DeleteModel(
            name="PaymentTransaction",
        ),
        migrations.RemoveField(
            model_name="trial",
            name="strategy",
        ),
        migrations.AddIndex(
            model_name="paypalpayment",
            index=models.Index(
                fields=["user", "status"], name="payments_pa_user_id_a3f64e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paypalpayment",
            index=models.Index(
                fields=["paypal_order_id"], name="payments_pa_paypal__81ba54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trialabuselog",
            index=models.Index(
                fields=["email", "machine_id_hash"], name="payments_tr_email_b15ca5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trialabuselog",
            index=models.Index(
                fields=["attempted_at"], name="payments_tr_attempt_9fdcbb_idx"
            ),
        ),
        migrations.DeleteModel(
            name="Strategy",
        ),
    ]
