# Generated by Django 5.0.14 on 2025-12-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="machine_id",
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_verification_token",
            field=models.CharField(
                blank=True, help_text="Token for email verification", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(
                default=False, help_text="Whether the user's email has been verified"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="machine_id_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA-256 hash of machine ID for strategy activation",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="machine_id_set_at",
            field=models.DateTimeField(
                blank=True, help_text="When the machine ID was registered", null=True
            ),
        ),
    ]
