# Generated by Django 5.0.14 on 2025-12-04 14:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal strategy identifier (e.g., 'momentum_v1')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="User-friendly name shown in UI", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Strategy description and details"),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly rental price (null if not available)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price_lifetime",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="One-time lifetime purchase price (null if not available)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this strategy is available for purchase",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Strategies",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="StrategyDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "downloaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("subscription", "Subscription"),
                            ("lifetime", "Lifetime"),
                        ],
                        help_text="Type of access at download time",
                        max_length=20,
                    ),
                ),
                (
                    "machine_id_hash",
                    models.CharField(
                        help_text="Machine ID hash at download time", max_length=64
                    ),
                ),
                (
                    "trial_triggered",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this download triggered a trial",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="dashboard.strategy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategy_downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-downloaded_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "strategy"],
                        name="dashboard_s_user_id_60f045_idx",
                    ),
                    models.Index(
                        fields=["downloaded_at"], name="dashboard_s_downloa_71889b_idx"
                    ),
                ],
            },
        ),
    ]
